In [1]:
from pyedflib import highlevel
import pandas as pd
import numpy as np
from glob import glob

In [21]:
data_list = glob('C:/Users/OH/python/Laboratory/sleep-edf-database-expanded-1.0.0/sleep-cassette/*.edf')
data = []

# for i in data_list:
#     temp = i.replace('C:/Users/OH/python/Laboratory/sleep-edf-database-expanded-1.0.0/sleep-cassette\\', '')
#     data.append(temp)
    
for i in data_list:
    temp = i.replace('\\', '/')
    data.append(temp)

trains = [x for x in data if x.endswith('PSG.edf')]
labels = [x for x in data if x.endswith('Hypnogram.edf')]

data

['C:/Users/OH/python/Laboratory/sleep-edf-database-expanded-1.0.0/sleep-cassette/SC4001E0-PSG.edf',
 'C:/Users/OH/python/Laboratory/sleep-edf-database-expanded-1.0.0/sleep-cassette/SC4001EC-Hypnogram.edf',
 'C:/Users/OH/python/Laboratory/sleep-edf-database-expanded-1.0.0/sleep-cassette/SC4002E0-PSG.edf',
 'C:/Users/OH/python/Laboratory/sleep-edf-database-expanded-1.0.0/sleep-cassette/SC4002EC-Hypnogram.edf',
 'C:/Users/OH/python/Laboratory/sleep-edf-database-expanded-1.0.0/sleep-cassette/SC4011E0-PSG.edf',
 'C:/Users/OH/python/Laboratory/sleep-edf-database-expanded-1.0.0/sleep-cassette/SC4011EH-Hypnogram.edf',
 'C:/Users/OH/python/Laboratory/sleep-edf-database-expanded-1.0.0/sleep-cassette/SC4012E0-PSG.edf',
 'C:/Users/OH/python/Laboratory/sleep-edf-database-expanded-1.0.0/sleep-cassette/SC4012EC-Hypnogram.edf',
 'C:/Users/OH/python/Laboratory/sleep-edf-database-expanded-1.0.0/sleep-cassette/SC4021E0-PSG.edf',
 'C:/Users/OH/python/Laboratory/sleep-edf-database-expanded-1.0.0/sleep-cass

In [23]:
highlevel.read_edf(trains[0])

([array([ 5.01684982, -2.57875458,  1.35970696, ...,  5.2981685 ,
         -4.64175824,  6.61098901]),
  array([-2.46739927,  1.46739927, -4.0989011 , ..., -3.04322344,
         -3.71501832,  1.75531136]),
  array([ 16.50866911,  16.01587302,   9.60952381, ...,  69.73064713,
          80.57216117, 102.25518926]),
  array([-482.,  628.,  -95., ...,  145.,  100.,  125.]),
  array([3.552, 3.49 , 3.476, ..., 3.546, 3.666, 3.582]),
  array([37.20645161, 37.22795699, 37.23655914, ..., 37.43978495,
         37.45053763, 37.43225806]),
  array([920., 899., 919., ..., 884., 898., 898.])],
 [{'label': 'EEG Fpz-Cz',
   'dimension': 'uV',
   'sample_rate': 3000.0,
   'sample_frequency': 3000.0,
   'physical_max': 192.0,
   'physical_min': -192.0,
   'digital_max': 2047,
   'digital_min': -2048,
   'prefilter': 'HP:0.5Hz LP:100Hz [enhanced cassette BW]',
   'transducer': 'Ag-AgCl electrodes'},
  {'label': 'EEG Pz-Oz',
   'dimension': 'uV',
   'sample_rate': 3000.0,
   'sample_frequency': 3000.0,
  

In [6]:
highlevel.read_edf(trains[0])[0]

[array([ 5.01684982, -2.57875458,  1.35970696, ...,  5.2981685 ,
        -4.64175824,  6.61098901]),
 array([-2.46739927,  1.46739927, -4.0989011 , ..., -3.04322344,
        -3.71501832,  1.75531136]),
 array([ 16.50866911,  16.01587302,   9.60952381, ...,  69.73064713,
         80.57216117, 102.25518926]),
 array([-482.,  628.,  -95., ...,  145.,  100.,  125.]),
 array([3.552, 3.49 , 3.476, ..., 3.546, 3.666, 3.582]),
 array([37.20645161, 37.22795699, 37.23655914, ..., 37.43978495,
        37.45053763, 37.43225806]),
 array([920., 899., 919., ..., 884., 898., 898.])]

In [24]:
highlevel.read_edf(trains[0])[1]

[{'label': 'EEG Fpz-Cz',
  'dimension': 'uV',
  'sample_rate': 3000.0,
  'sample_frequency': 3000.0,
  'physical_max': 192.0,
  'physical_min': -192.0,
  'digital_max': 2047,
  'digital_min': -2048,
  'prefilter': 'HP:0.5Hz LP:100Hz [enhanced cassette BW]',
  'transducer': 'Ag-AgCl electrodes'},
 {'label': 'EEG Pz-Oz',
  'dimension': 'uV',
  'sample_rate': 3000.0,
  'sample_frequency': 3000.0,
  'physical_max': 196.0,
  'physical_min': -197.0,
  'digital_max': 2047,
  'digital_min': -2048,
  'prefilter': 'HP:0.5Hz LP:100Hz [enhanced cassette BW]',
  'transducer': 'Ag-AgCl electrodes'},
 {'label': 'EOG horizontal',
  'dimension': 'uV',
  'sample_rate': 3000.0,
  'sample_frequency': 3000.0,
  'physical_max': 1009.0,
  'physical_min': -1009.0,
  'digital_max': 2047,
  'digital_min': -2048,
  'prefilter': 'HP:0.5Hz LP:100Hz [enhanced cassette BW]',
  'transducer': 'Ag-AgCl electrodes'},
 {'label': 'Resp oro-nasal',
  'dimension': '',
  'sample_rate': 30.0,
  'sample_frequency': 30.0,
  'ph

In [25]:
df = pd.DataFrame(highlevel.read_edf(trains[0])[0]).T
df.columns = ['EEG Fpz-Cz','EEG Pz-Oz','EOG horizontal','Resp oro-nasal',
              'EMG submental','Temp rectal','Event marker']
df

EEG Fpz-Cz  EEG Pz-Oz  EOG horizontal  Resp oro-nasal  EMG submental  \
0          5.016850  -2.467399       16.508669          -482.0          3.552   
1         -2.578755   1.467399       16.015873           628.0          3.490   
2          1.359707  -4.098901        9.609524           -95.0          3.476   
3         -2.391209  -2.659341        1.724786          -663.0          3.642   
4         -5.204396  -0.739927        7.638339           137.0          3.478   
...             ...        ...             ...             ...            ...   
7949995   11.299634  -6.882051       82.050549             NaN            NaN   
7949996    3.610256  -8.609524       62.338706             NaN            NaN   
7949997    5.298168  -3.043223       69.730647             NaN            NaN   
7949998   -4.641758  -3.715018       80.572161             NaN            NaN   
7949999    6.610989   1.755311      102.255189             NaN            NaN   

         Temp rectal  Event marker  
0          37.206452         920.0  
1          37.227957         899.0  
2          37.236559         919.0  
3          37.223656         912.0  
4          37.230108         926.0  
...              ...           ...  
7949995          NaN           NaN  
7949996          NaN           NaN  
7949997          NaN           NaN  
7949998          NaN           NaN  
7949999          NaN           NaN  

[7950000 rows x 7 columns]

In [71]:
highlevel.read_edf(labels[0])[2]['annotations']

[[0.0, 30630.0, 'Sleep stage W'],
 [30630.0, 120.0, 'Sleep stage 1'],
 [30750.0, 390.0, 'Sleep stage 2'],
 [31140.0, 30.0, 'Sleep stage 3'],
 [31170.0, 30.0, 'Sleep stage 2'],
 [31200.0, 150.0, 'Sleep stage 3'],
 [31350.0, 30.0, 'Sleep stage 4'],
 [31380.0, 60.0, 'Sleep stage 3'],
 [31440.0, 60.0, 'Sleep stage 4'],
 [31500.0, 30.0, 'Sleep stage 3'],
 [31530.0, 120.0, 'Sleep stage 4'],
 [31650.0, 30.0, 'Sleep stage 3'],
 [31680.0, 120.0, 'Sleep stage 4'],
 [31800.0, 30.0, 'Sleep stage W'],
 [31830.0, 60.0, 'Sleep stage 3'],
 [31890.0, 60.0, 'Sleep stage 2'],
 [31950.0, 120.0, 'Sleep stage 3'],
 [32070.0, 30.0, 'Sleep stage 4'],
 [32100.0, 30.0, 'Sleep stage 3'],
 [32130.0, 120.0, 'Sleep stage 4'],
 [32250.0, 210.0, 'Sleep stage 2'],
 [32460.0, 30.0, 'Sleep stage 3'],
 [32490.0, 60.0, 'Sleep stage 2'],
 [32550.0, 120.0, 'Sleep stage 3'],
 [32670.0, 30.0, 'Sleep stage 1'],
 [32700.0, 150.0, 'Sleep stage 2'],
 [32850.0, 60.0, 'Sleep stage 3'],
 [32910.0, 30.0, 'Sleep stage 2'],
 [32940.0, 

In [72]:
df1 = pd.DataFrame(highlevel.read_edf(labels[0])[2]['annotations'])
df1.columns = ['time', 'duration', 'sleep_stage']
df1

time  duration    sleep_stage
0        0.0   30630.0  Sleep stage W
1    30630.0     120.0  Sleep stage 1
2    30750.0     390.0  Sleep stage 2
3    31140.0      30.0  Sleep stage 3
4    31170.0      30.0  Sleep stage 2
..       ...       ...            ...
149  51540.0      30.0  Sleep stage 1
150  51570.0     540.0  Sleep stage W
151  52110.0     150.0  Sleep stage 1
152  52260.0   27240.0  Sleep stage W
153  79500.0    6900.0  Sleep stage ?

[154 rows x 3 columns]

In [73]:
df1['sleep_stage'].value_counts()

Sleep stage 3    48
Sleep stage 2    40
Sleep stage 1    24
Sleep stage 4    23
Sleep stage W    12
Sleep stage R     6
Sleep stage ?     1
Name: sleep_stage, dtype: int64